### ISSUE TITLE
插件ChatWaifu触发事件normal_message_responded时发生错误

### ISSUE THREAD

**Issue by GTian28** [dominoar/QChatPlugins#11]
报错如下

[2023-02-23 21:40:26.689] host.py (306) - [ERROR] : 插件ChatWaifu触发事件normal_message_responded时发生错误
[2023-02-23 21:40:26.698] host.py (307) - [ERROR] : Traceback (most recent call last):
  File "/bot/pkg/plugin/host.py", line 296, in emit
    hook(plugin['instance'], **kwargs)
  File "/bot/plugins/QChatPlugins/ChatWaifu/main.py", line 116, in group_normal_message_received
    self_host.send_group_message(launcher_id, voice)
  File "/bot/pkg/plugin/host.py", line 265, in send_group_message
    asyncio.run(self.get_bot().send_group_message(group, message))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 430, in __call__
    return await self.set(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 398, in set
    return await self._call_api(
  File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 386, in _call_api
    return await api.call(self.api_provider, method, response_type)
  File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 318, in call
    raw_response = await self._call(api_provider, method)
  File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 304, in _call
    return await api_provider.call_api(
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 320, in call_api
    return await self._adapter.call_api(api, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 236, in call_api
    return await self._recv(sync_id)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 165, in _recv
    raise exceptions.ApiError(data)
mirai.exceptions.ApiError: (500, '[ERROR 500]mirai 内部错误。', 'message is empty')

之前有一个issue和我这个报错基本一样，区别就是他最后apierror是(5, '[ERROR 5]发送消息目标不存在，或指定对象不存在。', '指定对象不存在')，而我的apierror是(500, '[ERROR 500]mirai 内部错误。', 'message is empty')。已经尝试过把switch.json提到plugins目录，打开switch.json，更改path。但仍无法解决。

**Comment by qkhill** [comment]
我也是一样的错误，请问你有解决吗

**Comment by GTian28** [comment]
> 我也是一样的错误，请问你有解决吗

没有

**Comment by qkhill** [comment]
你是什么环境呢，我是Linux环境，现在已经解决了
https://github.com/dominoar/QChatPlugins/issues/14

**Comment by GTian28** [comment]
> 你是什么环境呢，我是Linux环境，现在已经解决了 #14

我也是linux，你是咋解决的？

**Comment by qkhill** [comment]
看这个----->https://github.com/dominoar/QChatPlugins/issues/14

**Comment by GTian28** [comment]
> 看这个----->#14

哦哦，没注意，谢谢
