### ISSUE TITLE
Linux下的适配问题

### ISSUE THREAD

**Issue by qkhill** [dominoar/QChatPlugins#14]
作者大大好像没太管Linux下的情况。
我不是很懂python，但运行时发现了一些Linux下适配的问题
Linux下，文件夹路径要从 “\\” 改为 "/" , 如下图，除了这里还有一些别的地方也要修改
![图片](https://user-images.githubusercontent.com/25356807/223312992-fa9e7a3c-b310-408a-bbeb-d3b8c902de40.png)
此外
Linux下使用的pcm转silk应该为图上所示的encoder，之前使用的脚本是将silk转其他格式的，此外要注意用&&，不然可能出现wav没转完pcm，又跑pcm转silk的情况
https://github.com/kn007/silk-v3-decoder
这个程序需到这个项目上拉下源码，再到silk目录下编译
`make encoder`
这样做，Linux下基本可以跑通
![图片](https://user-images.githubusercontent.com/25356807/223314108-cb4ce25d-48ae-4a24-9a99-454b06fbfcfd.png)
但是测试发现持续对话时直接出现了崩溃的情况，不知道windows下运行会不会有这个问题，希望作者大大可以解答一下
![图片](https://user-images.githubusercontent.com/25356807/223314340-bced98bd-58a9-4a7f-a38e-323400fd7a00.png)

**Comment by qkhill** [comment]
出现killed档案大概率是因为我的linux内存不够了。。。
不过按我上面的方法可以适配到Linux，希望作者可以更新支持一下

**Comment by dantepayne** [comment]
你好，我在ubantu下执行silk-v3-decoder根目录下make encoder时报错了，信息为：/usr/bin/ld: 找不到 -lSKP_SILK_SDK: 没有那个文件或目录
是否是环境的问题？

**Comment by qkhill** [comment]
> 你好，我在ubantu下执行silk-v3-decoder根目录下make encoder时报错了，信息为：/usr/bin/ld: 找不到 -lSKP_SILK_SDK: 没有那个文件或目录 是否是环境的问题？

这是因为依赖库还没生成，你先执行make，再执行make encoder就可以了

**Comment by dantepayne** [comment]
好的，感谢！

**Comment by dantepayne** [comment]
> > 你好，我在ubantu下执行silk-v3-decoder根目录下make encoder时报错了，信息为：/usr/bin/ld: 找不到 -lSKP_SILK_SDK: 没有那个文件或目录 是否是环境的问题？
> 
> 这是因为依赖库还没生成，你先执行make，再执行make encoder就可以了

![~1Y4BEIAR 2AOL76L~34I_Y](https://user-images.githubusercontent.com/100111039/226554198-662e3c0b-05bc-4b6b-9273-f883472fbe17.png)
我按照您的方式去改了，但是仍然出现issue2的错误。
错误内容为：FileNotFoundError:[Erro 2]没有那个文件或目录：‘/home/dante/QChatBot\\model\\ChatWaifu\\model\\CN\\config.json’
很明显这是文件夹没有适配linux系统的情况，但是我不知道在哪里可以修改。

**Comment by dantepayne** [comment]
完整报错在这里
Traceback (most recent call last):
  File "/home/dante/QChatBot/QChatGPT_template/plugins/ChatWaifu/main.py", line 40, in process_mod
    model.ChatWaifu.ChatWaifu_marai.generateSound("[ZH]" + answer + "[ZH]", old_msg=answer, language="ch",
  File "/home/dante/QChatBot/QChatGPT_template/model/ChatWaifu/ChatWaifu_marai.py", line 144, in generateSound
    hps_ms = utils.get_hparams_from_file(config)
  File "/home/dante/QChatBot/QChatGPT_template/model/ChatWaifu/utils.py", line 65, in get_hparams_from_file
    with open(config_path, "r") as f:
FileNotFoundError: [Errno 2] 没有那个文件或目录: '/home/dante/QChatBot/QChatGPT_template\\model\\ChatWaifu\\model\\CN\\config.json'
[2023-03-21 16:36:09.336] host.py (331) - [ERROR] : 插件ChatWaifu触发事件normal_message_responded时发生错误
[2023-03-21 16:36:09.348] host.py (332) - [ERROR] : Traceback (most recent call last):
  File "/home/dante/QChatBot/QChatGPT_template/pkg/plugin/host.py", line 325, in emit
    hook(plugin['instance'], **kwargs)
  File "/home/dante/QChatBot/QChatGPT_template/plugins/ChatWaifu/main.py", line 116, in group_normal_message_received
    self_host.send_group_message(launcher_id, voice)
  File "/home/dante/QChatBot/QChatGPT_template/pkg/plugin/host.py", line 286, in send_group_message
    asyncio.run(self.get_bot().send_group_message(group, message))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/dante/.local/lib/python3.10/site-packages/mirai/models/api.py", line 415, in __call__
    return await self.set(*args, **kwargs)
  File "/home/dante/.local/lib/python3.10/site-packages/mirai/models/api.py", line 383, in set
    return await self._call_api(
  File "/home/dante/.local/lib/python3.10/site-packages/mirai/models/api.py", line 373, in _call_api
    return await api.call(self.api_provider, method, response_type)
  File "/home/dante/.local/lib/python3.10/site-packages/mirai/models/api.py", line 304, in call
    raw_response = await api_provider.call_api(
  File "/home/dante/.local/lib/python3.10/site-packages/mirai/bot.py", line 91, in call_api
    return await self._adapter.call_api(api, *args, **kwargs)
  File "/home/dante/.local/lib/python3.10/site-packages/mirai/adapters/websocket.py", line 236, in call_api
    return await self._recv(sync_id)
  File "/home/dante/.local/lib/python3.10/site-packages/mirai/adapters/websocket.py", line 165, in _recv
    raise exceptions.ApiError(data)
mirai.exceptions.ApiError: (500, '[ERROR 500]mirai 内部错误。', 'message is empty')

**Comment by qkhill** [comment]
> 完整报错在这里 Traceback (most recent call last): File "/home/dante/QChatBot/QChatGPT_template/plugins/ChatWaifu/main.py", line 40, in process_mod model.ChatWaifu.ChatWaifu_marai.generateSound("[ZH]" + answer + "[ZH]", old_msg=answer, language="ch", File "/home/dante/QChatBot/QChatGPT_template/model/ChatWaifu/ChatWaifu_marai.py", line 144, in generateSound hps_ms = utils.get_hparams_from_file(config) File "/home/dante/QChatBot/QChatGPT_template/model/ChatWaifu/utils.py", line 65, in get_hparams_from_file with open(config_path, "r") as f: FileNotFoundError: [Errno 2] 没有那个文件或目录: '/home/dante/QChatBot/QChatGPT_template\model\ChatWaifu\model\CN\config.json' [2023-03-21 16:36:09.336] host.py (331) - [ERROR] : 插件ChatWaifu触发事件normal_message_responded时发生错误 [2023-03-21 16:36:09.348] host.py (332) - [ERROR] : Traceback (most recent call last): File "/home/dante/QChatBot/QChatGPT_template/pkg/plugin/host.py", line 325, in emit hook(plugin['instance'], **kwargs) File "/home/dante/QChatBot/QChatGPT_template/plugins/ChatWaifu/main.py", line 116, in group_normal_message_received self_host.send_group_message(launcher_id, voice) File "/home/dante/QChatBot/QChatGPT_template/pkg/plugin/host.py", line 286, in send_group_message asyncio.run(self.get_bot().send_group_message(group, message)) File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete return future.result() File "/home/dante/.local/lib/python3.10/site-packages/mirai/models/api.py", line 415, in **call** return await self.set(*args, **kwargs) File "/home/dante/.local/lib/python3.10/site-packages/mirai/models/api.py", line 383, in set return await self._call_api( File "/home/dante/.local/lib/python3.10/site-packages/mirai/models/api.py", line 373, in _call_api return await api.call(self.api_provider, method, response_type) File "/home/dante/.local/lib/python3.10/site-packages/mirai/models/api.py", line 304, in call raw_response = await api_provider.call_api( File "/home/dante/.local/lib/python3.10/site-packages/mirai/bot.py", line 91, in call_api return await self._adapter.call_api(api, *args, **kwargs) File "/home/dante/.local/lib/python3.10/site-packages/mirai/adapters/websocket.py", line 236, in call_api return await self._recv(sync_id) File "/home/dante/.local/lib/python3.10/site-packages/mirai/adapters/websocket.py", line 165, in _recv raise exceptions.ApiError(data) mirai.exceptions.ApiError: (500, '[ERROR 500]mirai 内部错误。', 'message is empty')

还是路径的问题，作者不只上面所说的那一处路径没适配，比如还有下面这里；我的Linux主机配置太低，运行会被系统killed，所以我把这个模块删了；我记得还有几处地方也是需要修改路径的，你多找找
![图片](https://user-images.githubusercontent.com/25356807/226557715-fc8732d3-df84-4027-b606-99e61a901f89.png)

**Comment by dantepayne** [comment]
> > 完整报错在这里 Traceback (most recent call last): File "/home/dante/QChatBot/QChatGPT_template/plugins/ChatWaifu/main.py", line 40, in process_mod model.ChatWaifu.ChatWaifu_marai.generateSound("[ZH]" + answer + "[ZH]", old_msg=answer, language="ch", File "/home/dante/QChatBot/QChatGPT_template/model/ChatWaifu/ChatWaifu_marai.py", line 144, in generateSound hps_ms = utils.get_hparams_from_file(config) File "/home/dante/QChatBot/QChatGPT_template/model/ChatWaifu/utils.py", line 65, in get_hparams_from_file with open(config_path, "r") as f: FileNotFoundError: [Errno 2] 没有那个文件或目录: '/home/dante/QChatBot/QChatGPT_template\model\ChatWaifu\model\CN\config.json' [2023-03-21 16:36:09.336] host.py (331) - [ERROR] : 插件ChatWaifu触发事件normal_message_responded时发生错误 [2023-03-21 16:36:09.348] host.py (332) - [ERROR] : Traceback (most recent call last): File "/home/dante/QChatBot/QChatGPT_template/pkg/plugin/host.py", line 325, in emit hook(plugin['instance'], **kwargs) File "/home/dante/QChatBot/QChatGPT_template/plugins/ChatWaifu/main.py", line 116, in group_normal_message_received self_host.send_group_message(launcher_id, voice) File "/home/dante/QChatBot/QChatGPT_template/pkg/plugin/host.py", line 286, in send_group_message asyncio.run(self.get_bot().send_group_message(group, message)) File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete return future.result() File "/home/dante/.local/lib/python3.10/site-packages/mirai/models/api.py", line 415, in **call** return await self.set(*args, **kwargs) File "/home/dante/.local/lib/python3.10/site-packages/mirai/models/api.py", line 383, in set return await self._call_api( File "/home/dante/.local/lib/python3.10/site-packages/mirai/models/api.py", line 373, in _call_api return await api.call(self.api_provider, method, response_type) File "/home/dante/.local/lib/python3.10/site-packages/mirai/models/api.py", line 304, in call raw_response = await api_provider.call_api( File "/home/dante/.local/lib/python3.10/site-packages/mirai/bot.py", line 91, in call_api return await self._adapter.call_api(api, *args, **kwargs) File "/home/dante/.local/lib/python3.10/site-packages/mirai/adapters/websocket.py", line 236, in call_api return await self._recv(sync_id) File "/home/dante/.local/lib/python3.10/site-packages/mirai/adapters/websocket.py", line 165, in _recv raise exceptions.ApiError(data) mirai.exceptions.ApiError: (500, '[ERROR 500]mirai 内部错误。', 'message is empty')
> 
> 还是路径的问题，作者不只上面所说的那一处路径没适配，比如还有下面这里；我的Linux主机配置太低，运行会被系统killed，所以我把这个模块删了；我记得还有几处地方也是需要修改路径的，你多找找 ![图片](https://user-images.githubusercontent.com/25356807/226557715-fc8732d3-df84-4027-b606-99e61a901f89.png)

谢谢您，其余需要适配的文件在ChatWaifu_marai.py中，如果其他人碰到这样的问题，请在这个.py中进行集中处理。
