### ISSUE TITLE
插件ChatWaifu触发事件normal_message_responded时发生错误

### ISSUE THREAD

**Issue by soysong7788** [dominoar/QChatPlugins#2]
问题现象：没有语音对话弹出，仅弹出文字对话。

问题发生的背景：mirai登录正常，机器人登录正常。但首次开启对话，bot即报错如下：

2023-02-04 04:50:10 - INFO     [WebSocket] 成功登录到账号104XXX8040。
[2023-02-04 04:50:10.085] websocket.py (194) - [INFO] : [WebSocket] 成功登录到账号104XXX8040。
2023-02-04 04:50:10 - INFO     [WebSocket] 机器人开始运行。按 Ctrl + C 停止。
[2023-02-04 04:50:10.087] websocket.py (250) - [INFO] : [WebSocket] 机器人开始运行。按 Ctrl + C 停止。
[2023-02-04 04:50:20.978] main.py (193) - [INFO] : 程序启动完成,如长时间未显示 ”成功登录到账号xxxxx“ ,并且不回复消息, 请查看 https://github.com/RockChinQ/QChatGPT/issues/37
[2023-02-04 04:50:26.448] main.py (206) - [INFO] : 当前已是最新版本
[2023-02-04 04:50:28.658] message.py (14) - [INFO] : [person_527270940]发送消息:你好
[2023-02-04 04:50:33.190] utils.py (59) - [INFO] : Loaded checkpoint 'E:\一键上手语音版最终\QQbot+VITS\QQbot\bot\QChatGPT\model\ChatWaifu\model\CN\model.pth' (iteration None)
[model.ChatWaifu]Successfully saved!
[2023-02-04 04:50:37.746] host.py (273) - [ERROR] : 插件ChatWaifu触发事件normal_message_responded时发生错误
[2023-02-04 04:50:37.748] host.py (274) - [ERROR] : Traceback (most recent call last):
  File "E:\一键上手语音版最终\QQbot+VITS\QQbot\bot\QChatGPT\.\pkg\plugin\host.py", line 263, in emit
    hook(plugin['instance'], **kwargs)
  File "E:\一键上手语音版最终\QQbot+VITS\QQbot\bot\QChatGPT\.\plugins\QchatPlugins-master\ChatWaifu\main.py", line 33, in group_normal_message_received
    kwargs['host'].send_group_message(kwargs["launcher_id"], msg)
  File "E:\一键上手语音版最终\QQbot+VITS\QQbot\bot\QChatGPT\.\pkg\plugin\host.py", line 232, in send_group_message
    asyncio.run(self.get_bot().send_group_message(group, message))
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "E:\一键上手语音版最终\QQbot+VITS\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 415, in __call__
    return await self.set(*args, **kwargs)
  File "E:\一键上手语音版最终\QQbot+VITS\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 383, in set
    return await self._call_api(
  File "E:\一键上手语音版最终\QQbot+VITS\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 373, in _call_api
    return await api.call(self.api_provider, method, response_type)
  File "E:\一键上手语音版最终\QQbot+VITS\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 304, in call
    raw_response = await api_provider.call_api(
  File "E:\一键上手语音版最终\QQbot+VITS\QQbot\bot\python\lib\site-packages\mirai\bot.py", line 91, in call_api
    return await self._adapter.call_api(api, *args, **kwargs)
  File "E:\一键上手语音版最终\QQbot+VITS\QQbot\bot\python\lib\site-packages\mirai\adapters\websocket.py", line 236, in call_api
    return await self._recv(sync_id)
  File "E:\一键上手语音版最终\QQbot+VITS\QQbot\bot\python\lib\site-packages\mirai\adapters\websocket.py", line 165, in _recv
    raise exceptions.ApiError(data)
mirai.exceptions.ApiError: (5, '[ERROR 5]发送消息目标不存在，或指定对象不存在。', '指定对象不存在')

[2023-02-04 04:50:37.749] process.py (119) - [INFO] : 回复[person_527270940]文字消息:你好！我是机器人小 助手，有什么可以帮助您的吗？

**Comment by ShinoKana** [comment]
我有过类似的问题，是因为model, plugin和这个项目本身反复下载导致的，解决方法是switch.json提到plugins目录，打开switch.json，更改path为plugins/BanMassage/main.py，其他插件的path同理。

**Comment by dominoar** [comment]
我明白了，感谢反馈


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dominoar/QChatPlugins"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月4日(星期六) 晚上11:42
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [dominoar/QChatPlugins] 插件ChatWaifu触发事件normal_message_responded时发生错误 (Issue #2)





 
我有过类似的问题，是因为model, plugin和这个项目本身反复下载导致的，解决方法是switch.json提到plugins目录，打开switch.json，更改path为plugins/BanMassage/main.py，其他插件的path同理。

**Comment by dominoar** [comment]
我已经了解你的问题，在私聊中，mirai是不支持私聊发送语音的，会出现mirai内部错误。

**Comment by dominoar** [comment]
项目已经更新了GoCq的私聊发送解决方案

**Comment by soysong7788** [comment]
好的谢谢！感谢指导！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月04日 23:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [dominoar/QChatPlugins] 插件ChatWaifu触发事件normal_message_responded时发生错误 (Issue #2) |

我有过类似的问题，是因为model, plugin和这个项目本身反复下载导致的，解决方法是switch.json提到plugins目录，打开switch.json，更改path为plugins/BanMassage/main.py，其他插件的path同理。
