### ISSUE TITLE
BUG: 加载模块: plugins/ChatWaifu/main.py 失败

### ISSUE THREAD

**Issue by quin2233** [dominoar/QChatPlugins#23]
版本：python3.9

错误： 
host.py (83) - [ERROR] : 加载模块: plugins/ChatWaifu/main.py 失败: (<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'scipy'"), <traceback object at 0x000002075FC90940>)
Traceback (most recent call last):
  File "E:\QChat\QChatGPT\.\pkg\plugin\host.py", line 80, in walk_plugin_path
    importlib.import_module(module.__name__ + '.' + item.name)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\QChat\QChatGPT\.\plugins\ChatWaifu\main.py", line 18, in <module>
    import model.ChatWaifu.ChatWaifu_marai
  File "E:\QChat\QChatGPT\.\model\ChatWaifu\ChatWaifu_marai.py", line 8, in <module>
    from scipy.io.wavfile import write  # wav
ModuleNotFoundError: No module named 'scipy'

每次跑run-bot.bat就会出现这个错误，可是我已经安装了scipy，更换大小写字母成SciPy也没用
![image](https://user-images.githubusercontent.com/129948025/230379006-d1852272-9ed7-4134-989c-25eadbba0e81.png)

**Comment by quin2233** [comment]
已解决，我安装qchatgpt时是自动安装，运行run-bot.bat只会在项目的python文件夹下运行，所以无法调用模块
