### ISSUE TITLE
已经安装过scipy仍然提示No module named 'scipy'

### ISSUE THREAD

**Issue by WwlWss** [dominoar/QChatPlugins#25]
[2023-04-14 01:18:10.264] reloader.py (17) - [INFO] : reload module: QChatPlugins.ChatWaifu.main, path: QChatPlugins/ChatWaifu/main.py
Exception in thread Thread-5 (reload_task):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\QChatGPT\QChatGPT\.\pkg\qqbot\cmds\system\reload.py", line 19, in reload_task
    pkg.utils.reloader.reload_all()
  File "D:\QChatGPT\QChatGPT\.\pkg\utils\reloader.py", line 49, in reload_all
    walk(plugins)
  File "D:\QChatGPT\QChatGPT\.\pkg\utils\reloader.py", line 15, in walk
    walk(__import__(module.__name__ + '.' + item.name, fromlist=['']), prefix + item.name + '.', path_prefix + item.name + '/')
  File "D:\QChatGPT\QChatGPT\.\pkg\utils\reloader.py", line 15, in walk
    walk(__import__(module.__name__ + '.' + item.name, fromlist=['']), prefix + item.name + '.', path_prefix + item.name + '/')
  File "D:\QChatGPT\QChatGPT\.\pkg\utils\reloader.py", line 19, in walk
    importlib.reload(__import__(module.__name__ + '.' + item.name, fromlist=['']))
  File "D:\QChatGPT\QChatGPT\.\plugins\QChatPlugins\ChatWaifu\main.py", line 18, in <module>
    import model.ChatWaifu.ChatWaifu_marai
  File "D:\QChatGPT\QChatGPT\.\model\ChatWaifu\ChatWaifu_marai.py", line 8, in <module>
    from scipy.io.wavfile import write  # wav
ModuleNotFoundError: No module named 'scipy'

**Comment by WwlWss** [comment]
![image](https://user-images.githubusercontent.com/90305844/231828455-e0e500d3-b6ed-4aa8-a043-7ad1397ada62.png)

**Comment by WwlWss** [comment]
![image](https://user-images.githubusercontent.com/90305844/231828571-532b7f80-662e-4294-afed-e2630bcf984a.png)
已经安装过scipy

**Comment by WwlWss** [comment]
应该没有启动其他的pythong版本，scipy是安装在最上面的
![image](https://user-images.githubusercontent.com/90305844/231836389-d40e8dda-d0bd-48ad-a9b1-7965e2d0a3bd.png)

**Comment by WwlWss** [comment]
已解决，原因是QChatGPT自己有个Python被先调用了
