### ISSUE TITLE
下载了对应的库但运行时仍然显示不能找到对应module

### ISSUE THREAD

**Issue by ShinoKana** [dominoar/QChatPlugins#3]
如题，已经重启过，就算不适用banmassage这个插件，其他插件也有类似问题

Database initialized.
[2023-02-04 17:04:32.765] keymgr.py (52) - [INFO] : 使用api-key:default
[2023-02-04 17:04:32.799] manager.py (77) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790]
[2023-02-04 17:04:32.799] host.py (60) - [INFO] : 加载插件
[2023-02-04 17:04:32.802] host.py (52) - [INFO] : 加载模块: plugins/BanMassage/main.py
[2023-02-04 17:04:44.803] main.py (193) - [INFO] : 程序启动完成,如长时间未显示 ”成功登录到账号xxxxx“ ,并且不回复消息,请查看 https://github.com/RockChinQ/QChatGPT/issues/37
Traceback (most recent call last):
  File "C:\Users\bot\qq\QChatGPT\main.py", line 279, in <module>
    main(True)
  File "C:\Users\bot\qq\QChatGPT\main.py", line 136, in main
    pkg.plugin.host.load_plugins()
  File "C:\Users\bot\qq\QChatGPT\.\pkg\plugin\host.py", line 62, in load_plugins
    walk_plugin_path(__import__('plugins'))
  File "C:\Users\bot\qq\QChatGPT\.\pkg\plugin\host.py", line 48, in walk_plugin_path
    walk_plugin_path(__import__(module.__name__ + '.' + item.name, fromlist=['']),
  File "C:\Users\bot\qq\QChatGPT\.\pkg\plugin\host.py", line 55, in walk_plugin_path
    importlib.import_module(module.__name__ + '.' + item.name)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\bot\qq\QChatGPT\.\plugins\BanMassage\main.py", line 9, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

(base) C:\Users\bot\qq\QChatGPT>pip list
Package                            Version
---------------------------------------
...
PyYAML                             6.0
...

**Comment by ShinoKana** [comment]
已经解决，在bot/python中重新装plugins requirements.txt中的包，因为原先的包的安装路径和run-bot.bat需要的路径不符。
cd QChatGPT
..\python\python.exe main.py
pause
这是run-bot.bat中提到的路径。
但可能不是最优解，因为这样导致python中的lib特别大，有很多包都需要重装

**Comment by dominoar** [comment]
请你更新项目，使用项目中的requri……txt文件下载所有的依赖


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dominoar/QChatPlugins"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月4日(星期六) 下午5:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[dominoar/QChatPlugins] 下载了对应的库但运行时仍然显示不能找到对应module (Issue #3)





 
如题，已经重启过，就算不适用banmassage这个插件，其他插件也有类似问题
 
Database initialized.
 [2023-02-04 17:04:32.765] keymgr.py (52) - [INFO] : 使用api-key:default
 [2023-02-04 17:04:32.799] manager.py (77) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790]
 [2023-02-04 17:04:32.799] host.py (60) - [INFO] : 加载插件
 [2023-02-04 17:04:32.802] host.py (52) - [INFO] : 加载模块: plugins/BanMassage/main.py
 [2023-02-04 17:04:44.803] main.py (193) - [INFO] : 程序启动完成,如长时间未显示 ”成功登录到账号xxxxx“ ,并且不回复消息,请查看 RockChinQ/QChatGPT#37
 Traceback (most recent call last):
 File "C:\Users\bot\qq\QChatGPT\main.py", line 279, in 
 main(True)
 File "C:\Users\bot\qq\QChatGPT\main.py", line 136, in main
 pkg.plugin.host.load_plugins()
 File "C:\Users\bot\qq\QChatGPT.\pkg\plugin\host.py", line 62, in load_plugins
 walk_plugin_path(import('plugins'))
 File "C:\Users\bot\qq\QChatGPT.\pkg\plugin\host.py", line 48, in walk_plugin_path
 walk_plugin_path(import(module.name + '.' + item.name, fromlist=['']),
 File "C:\Users\bot\qq\QChatGPT.\pkg\plugin\host.py", line 55, in walk_plugin_path
 importlib.import_module(module.name + '.' + item.name)
 File "importlib_init_.py", line 126, in import_module
 File "", line 1050, in _gcd_import
 File "", line 1027, in _find_and_load
 File "", line 1006, in _find_and_load_unlocked
 File "", line 688, in _load_unlocked
 File "", line 883, in exec_module
 File "", line 241, in _call_with_frames_removed
 File "C:\Users\bot\qq\QChatGPT.\plugins\BanMassage\main.py", line 9, in 
 import yaml
 ModuleNotFoundError: No module named 'yaml'
 
(base) C:\Users\bot\qq\QChatGPT&gt;pip list
 Package                            Version
 
...
 PyYAML                             6.0
 ...

**Comment by dominoar** [comment]
重新安装requirements并不会导致你的lib变大，因为你已经安装的包pip不会再次安装，而requirements是项目所有所需的依赖，一些不常用功能的依赖也在其中




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dominoar/QChatPlugins"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月4日(星期六) 晚上11:46
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [dominoar/QChatPlugins] 下载了对应的库但运行时仍然显示不能找到对应module (Issue #3)





 
已经解决，在bot/python中重新装plugins requirements.txt中的包，因为原先的包的安装路径和run-bot.bat需要的路径不符。
 cd QChatGPT
 ..\python\python.exe main.py
 pause
 这是run-bot.bat中提到的路径。
 但可能不是最优解，因为这样导致python中的lib特别大，有很多包都需要重装

**Comment by dominoar** [comment]
我希望你能附件你的项目目录截图与报错信息，方便我更清楚的查找问题


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dominoar/QChatPlugins"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月4日(星期六) 晚上11:46
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [dominoar/QChatPlugins] 下载了对应的库但运行时仍然显示不能找到对应module (Issue #3)





 
Closed #3 as completed.

**Comment by ShinoKana** [comment]
你好，关于closed的问题，我在0.png中的python重新装包，更改了switch.json的路径。然后出现了“插件ChatWaifu触发事件normal_message_responded时发生错误”类似的问题，不能生成语音，这时候我另外下载了gocq，启动.bat。随之语音可以生成并且发送，但是会出现超时的情况，反复发送同一条语音3遍，直到报错停止运行。然后我用bilibili demo当中的文件，更改了mirai的config，就可以生成语音并且发送消息，但是只有安卓手机可以听到这条语音，苹果和windows 电脑不能听到。


________________________________
