### ISSUE TITLE
【go-cqhttp】插件ChatWaifu触发事件normal_message_responded时发生错误Unknown message type

### ISSUE THREAD

**Issue by soysong7788** [dominoar/QChatPlugins#30]
请教多神！！！！我是用go-cqhttp登录的，运行bot，对话，然后只出现了文字，语音没有加载出来。气氛上是已经生成了语音了，但识别不了？请看一眼：（感激不尽~谢谢解答！）
Packet interval:                20 ms
Inband FEC used:                0
DTX used:                       0
Complexity:                     2
Target bitrate:                 25000 bps
Packets encoded:                240
File length:                    4.800 s
Time for encoding:              0.225 s (4.688% of realtime)
Average bitrate:                22.930 kbps
Active bitrate:                 23.221 kbps

[2023-05-08 01:52:25.732] main.py (60) - [INFO] : 语音silk生成成功！ヽ(￣▽￣)ﾉ
[2023-05-08 01:52:25.732] host.py (335) - [ERROR] : 插件ChatWaifu触发事件normal_message_responded时发生错误
[2023-05-08 01:52:25.732] host.py (336) - [ERROR] : Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Abot20230507\QChatGPT\.\pkg\plugin\host.py", line 329, in emit
    hook(plugin['instance'], **kwargs)
  File "C:\Users\Administrator\Desktop\Abot20230507\QChatGPT\.\plugins\ChatWaifu\main.py", line 116, in group_normal_message_received
    self_host.send_group_message(launcher_id, voice)
  File "C:\Users\Administrator\Desktop\Abot20230507\QChatGPT\.\pkg\plugin\host.py", line 290, in send_group_message
    self.get_bot_adapter().send_message("group", group, message)
  File "C:\Users\Administrator\Desktop\Abot20230507\QChatGPT\.\pkg\qqbot\sources\nakuru.py", line 197, in send_message
    converted_msg = self.message_converter.yiri2target(message) if not converted else message
  File "C:\Users\Administrator\Desktop\Abot20230507\QChatGPT\.\pkg\qqbot\sources\nakuru.py", line 26, in yiri2target
    raise Exception("Unknown message type: " + str(message_chain) + str(type(message_chain)))
Exception: Unknown message type: [语音]<class 'mirai.models.message.Voice'>

[2023-05-08 01:52:25.732] process.py (157) - [INFO] : 回复[group_146136054]文字消息:嗨，你这个普通人。【内心翻了个白眼，对方还是那么无聊】

**Comment by RockChinQ** [comment]
这个语音目前只支持mirai登录的

**Comment by soysong7788** [comment]
> 这个语音目前只支持mirai登录的

啊这种事情不要啊！！！！mirai总是45登不上去呢呜呜呜呜
