### ISSUE TITLE
bug 显示无法导入yaml

### ISSUE THREAD

**Issue by smz202000** [dominoar/QChatPlugins#8]
![6249bc262599e966.jpg](https://user-images.githubusercontent.com/69295615/219910362-9de8790e-b2af-4991-8c6b-dec5300e2d7b.jpg)
已安装yaml

**Comment by Reim** [comment]
python  pip 版本

**Comment by Reim** [comment]
Exception in thread Thread-251:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/bot/pkg/qqbot/command.py", line 309, in reload_task
    pkg.utils.reloader.reload_all()
  File "/bot/pkg/utils/reloader.py", line 40, in reload_all
    walk(plugins)
  File "/bot/pkg/utils/reloader.py", line 14, in walk
    walk(__import__(module.__name__ + '.' + item.name, fromlist=['']), prefix + item.name + '.')
  File "/bot/pkg/utils/reloader.py", line 17, in walk
    importlib.reload(__import__(module.__name__ + '.' + item.name, fromlist=['']))
  File "/bot/plugins/QCPNovelAi/main.py", line 22, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'


[root@hecs-149815 ~]# pip install pyyaml
Requirement already satisfied: pyyaml in /usr/local/python3/lib/python3.9/site-packages (6.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv


[root@hecs-149815 ~]# python -V
Python 3.9.15
[root@hecs-149815 ~]# pip -V
pip 23.0.1 from /usr/local/python3/lib/python3.9/site-packages/pip (python 3.9)

**Comment by dominoar** [comment]
pip install pyYAML

**Comment by 1293343374** [comment]
![image](https://user-images.githubusercontent.com/57089597/220908546-032f610e-b94c-40e1-b754-8dad665c70a4.png)

有回复但是没有生成语音
